server:
  port: 9092
spring:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.16.5:3306/news?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8
      username: root
      password: yjcsxdl123!@#
      initialSize: 5
      maxActive: 50
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 1800000
      maxEvictableIdleTimeMillis: 25200000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/qingmi/yi/**/mapping/*.xml
  typeAliasesPackage: com.qingmi.yi.**.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.gengyuhm: debug



